// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAna1kxrvLpNYi5S0wq8NYtUSOO_9Vg6c',
    appId: '1:970520097045:web:98e148f060a7768f1af91c',
    messagingSenderId: '970520097045',
    projectId: 'safi-3d6e2',
    authDomain: 'safi-3d6e2.firebaseapp.com',
    storageBucket: 'safi-3d6e2.firebasestorage.app',
    measurementId: 'G-3SRDT9VK54',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNFbTHDhHexab3aQ2ZV9a9yvPlmjy6hKM',
    appId: '1:970520097045:android:2bc6c99e2ed4b5551af91c',
    messagingSenderId: '970520097045',
    projectId: 'safi-3d6e2',
    storageBucket: 'safi-3d6e2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjnoD8rN_LEKwkJ2-8chdCQkf-qmpvE54',
    appId: '1:970520097045:ios:dd3092b6fe63e0651af91c',
    messagingSenderId: '970520097045',
    projectId: 'safi-3d6e2',
    storageBucket: 'safi-3d6e2.firebasestorage.app',
    iosBundleId: 'com.example.safi',
  );
}
