default_platform(:android)
platform :android do
  desc "Lane For Release New APK By Firebase App Distribution"
  lane :push_apk_by_distribution do
    sh "flutter clean"
    sh "flutter build apk --release"

    firebase_app_distribution(
      app: ENV['FIREBASE_APP_ID'],
      android_artifact_type: "APK",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-release.apk",
      testers: "anassef798@gmail.com",
      release_notes: "push new apk version",
      firebase_cli_token: ENV['FIREBASE_CLI_TOKEN']
      )
  end
end